<?php

declare(strict_types=1);

# Generated by the protocol buffer compiler (for Phluxor). DO NOT EDIT!
# source: websocket_remote.proto

namespace Phluxor\Remote\WebSocket\ProtoBuf;

use Phluxor\Remote\ProtoBuf\GetProcessDiagnosticsRequest;
use Phluxor\Remote\ProtoBuf\GetProcessDiagnosticsResponse;
use Phluxor\Remote\ProtoBuf\ListProcessesRequest;
use Phluxor\Remote\ProtoBuf\ListProcessesResponse;
use Phluxor\Remote\ProtoBuf\RemoteMessage;
use Phluxor\WebSocket;

interface RemotingInterface extends WebSocket\ServiceInterface
{
    public const string NAME = "/remote.Remoting";

    /**
     * @param WebSocket\ContextInterface $ctx
     * @param RemoteMessage $request
     * @return void
     *
     * @throws WebSocket\Exception\InvokeException
     */
    public function Receive(WebSocket\ContextInterface $ctx, RemoteMessage $request): void; // @phpcs:ignore

    /**
     * @param WebSocket\ContextInterface $ctx
     * @param ListProcessesRequest $request
     * @return ListProcessesResponse
     *
     * @throws WebSocket\Exception\InvokeException
     */
    public function ListProcesses(
        WebSocket\ContextInterface $ctx,
        ListProcessesRequest $request
    ): ListProcessesResponse; // @phpcs:ignore

    /**
     * @param WebSocket\ContextInterface $ctx
     * @param GetProcessDiagnosticsRequest $request
     * @return GetProcessDiagnosticsResponse
     *
     * @throws WebSocket\Exception\InvokeException
     */
    public function GetProcessDiagnostics(
        WebSocket\ContextInterface $ctx,
        GetProcessDiagnosticsRequest $request
    ): GetProcessDiagnosticsResponse; // @phpcs:ignore
}
