<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: websocket_remote.proto

namespace Phluxor\Remote\WebSocket\Metadata\ProtoBuf;

class WebsocketRemote
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \Phluxor\Remote\Metadata\ProtoBuf\Message::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\xFF\x02\x0A\x16websocket_remote.proto\x12\x06remote2\x81\x02\x0A\x08Remoting\x12=\x0A\x07Receive\x12\x15.remote.RemoteMessage\x1A\x15.remote.RemoteMessage\"\x00(\x010\x01\x12N\x0A\x0DListProcesses\x12\x1C.remote.ListProcessesRequest\x1A\x1D.remote.ListProcessesResponse\"\x00\x12f\x0A\x15GetProcessDiagnostics\x12\$.remote.GetProcessDiagnosticsRequest\x1A%.remote.GetProcessDiagnosticsResponse\"\x00BQ\xCA\x02!Phluxor\\Remote\\WebSocket\\ProtoBuf\xE2\x02*Phluxor\\Remote\\WebSocket\\Metadata\\ProtoBufb\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

