<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: message.proto

namespace Test\Metadata;

class Message
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            "\x0Au\x0A\x0Dmessage.proto\x12\x08protobuf\"\x0E\x0A\x0CHelloRequest\" \x0A\x0DHelloResponse\x12\x0F\x0A\x07Message\x18\x01 \x01(\x09B \xCA\x02\x0DTest\\ProtoBuf\xE2\x02\x0DTest\\Metadatab\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

