<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: message.proto

namespace Phluxor\Remote\ProtoBuf;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>remote.ConnectRequest</code>
 */
class ConnectRequest extends \Google\Protobuf\Internal\Message
{
    protected $connection_type;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Phluxor\Remote\ProtoBuf\ClientConnection $client_connection
     *     @type \Phluxor\Remote\ProtoBuf\ServerConnection $server_connection
     * }
     */
    public function __construct($data = NULL) {
        \Phluxor\Remote\Metadata\ProtoBuf\Message::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.remote.ClientConnection client_connection = 1;</code>
     * @return \Phluxor\Remote\ProtoBuf\ClientConnection|null
     */
    public function getClientConnection()
    {
        return $this->readOneof(1);
    }

    public function hasClientConnection()
    {
        return $this->hasOneof(1);
    }

    /**
     * Generated from protobuf field <code>.remote.ClientConnection client_connection = 1;</code>
     * @param \Phluxor\Remote\ProtoBuf\ClientConnection $var
     * @return $this
     */
    public function setClientConnection($var)
    {
        GPBUtil::checkMessage($var, \Phluxor\Remote\ProtoBuf\ClientConnection::class);
        $this->writeOneof(1, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.remote.ServerConnection server_connection = 2;</code>
     * @return \Phluxor\Remote\ProtoBuf\ServerConnection|null
     */
    public function getServerConnection()
    {
        return $this->readOneof(2);
    }

    public function hasServerConnection()
    {
        return $this->hasOneof(2);
    }

    /**
     * Generated from protobuf field <code>.remote.ServerConnection server_connection = 2;</code>
     * @param \Phluxor\Remote\ProtoBuf\ServerConnection $var
     * @return $this
     */
    public function setServerConnection($var)
    {
        GPBUtil::checkMessage($var, \Phluxor\Remote\ProtoBuf\ServerConnection::class);
        $this->writeOneof(2, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getConnectionType()
    {
        return $this->whichOneof("connection_type");
    }

}

