<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: message.proto

namespace Phluxor\Remote\ProtoBuf;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>remote.GetProcessDiagnosticsResponse</code>
 */
class GetProcessDiagnosticsResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string diagnostics_string = 1;</code>
     */
    protected $diagnostics_string = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $diagnostics_string
     * }
     */
    public function __construct($data = NULL) {
        \Phluxor\Remote\Metadata\ProtoBuf\Message::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string diagnostics_string = 1;</code>
     * @return string
     */
    public function getDiagnosticsString()
    {
        return $this->diagnostics_string;
    }

    /**
     * Generated from protobuf field <code>string diagnostics_string = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setDiagnosticsString($var)
    {
        GPBUtil::checkString($var, True);
        $this->diagnostics_string = $var;

        return $this;
    }

}

