<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: message.proto

namespace Phluxor\Remote\ProtoBuf;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>remote.MessageBatch</code>
 */
class MessageBatch extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated string type_names = 1;</code>
     */
    private $type_names;
    /**
     * Generated from protobuf field <code>repeated .actor.Pid targets = 2;</code>
     */
    private $targets;
    /**
     * Generated from protobuf field <code>repeated .remote.MessageEnvelope envelopes = 3;</code>
     */
    private $envelopes;
    /**
     * Generated from protobuf field <code>repeated .actor.Pid senders = 4;</code>
     */
    private $senders;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $type_names
     *     @type array<\Phluxor\ActorSystem\ProtoBuf\Pid>|\Google\Protobuf\Internal\RepeatedField $targets
     *     @type array<\Phluxor\Remote\ProtoBuf\MessageEnvelope>|\Google\Protobuf\Internal\RepeatedField $envelopes
     *     @type array<\Phluxor\ActorSystem\ProtoBuf\Pid>|\Google\Protobuf\Internal\RepeatedField $senders
     * }
     */
    public function __construct($data = NULL) {
        \Phluxor\Remote\Metadata\ProtoBuf\Message::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated string type_names = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getTypeNames()
    {
        return $this->type_names;
    }

    /**
     * Generated from protobuf field <code>repeated string type_names = 1;</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setTypeNames($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->type_names = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .actor.Pid targets = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getTargets()
    {
        return $this->targets;
    }

    /**
     * Generated from protobuf field <code>repeated .actor.Pid targets = 2;</code>
     * @param array<\Phluxor\ActorSystem\ProtoBuf\Pid>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setTargets($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Phluxor\ActorSystem\ProtoBuf\Pid::class);
        $this->targets = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .remote.MessageEnvelope envelopes = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getEnvelopes()
    {
        return $this->envelopes;
    }

    /**
     * Generated from protobuf field <code>repeated .remote.MessageEnvelope envelopes = 3;</code>
     * @param array<\Phluxor\Remote\ProtoBuf\MessageEnvelope>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setEnvelopes($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Phluxor\Remote\ProtoBuf\MessageEnvelope::class);
        $this->envelopes = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .actor.Pid senders = 4;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getSenders()
    {
        return $this->senders;
    }

    /**
     * Generated from protobuf field <code>repeated .actor.Pid senders = 4;</code>
     * @param array<\Phluxor\ActorSystem\ProtoBuf\Pid>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setSenders($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Phluxor\ActorSystem\ProtoBuf\Pid::class);
        $this->senders = $arr;

        return $this;
    }

}

