<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: message.proto

namespace Phluxor\Remote\ProtoBuf;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>remote.ServerConnection</code>
 */
class ServerConnection extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string SystemId = 1;</code>
     */
    protected $SystemId = '';
    /**
     * Generated from protobuf field <code>string Address = 2;</code>
     */
    protected $Address = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $SystemId
     *     @type string $Address
     * }
     */
    public function __construct($data = NULL) {
        \Phluxor\Remote\Metadata\ProtoBuf\Message::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string SystemId = 1;</code>
     * @return string
     */
    public function getSystemId()
    {
        return $this->SystemId;
    }

    /**
     * Generated from protobuf field <code>string SystemId = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setSystemId($var)
    {
        GPBUtil::checkString($var, True);
        $this->SystemId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string Address = 2;</code>
     * @return string
     */
    public function getAddress()
    {
        return $this->Address;
    }

    /**
     * Generated from protobuf field <code>string Address = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setAddress($var)
    {
        GPBUtil::checkString($var, True);
        $this->Address = $var;

        return $this;
    }

}

